server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 80
#测试环境MongoDB地址
spring:
    data:
        mongodb:
            uri: mongodb://192.168.2.133:27017/zydata

#Log4j2配置文件
logging:
      config: classpath:log4j2-dev.xml
