# spring
spring:
    # 环境 dev|test|pro
    profiles:
        active: dev
    aop:
      auto: true
    # jackson时间格式化
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    http:
        converters:
          preferred-json-mapper: fastjson
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
            enabled: true